package com.test.buzzer

import com.test.buzzer.driver.Note

object StarWars {
    val melody = arrayOf( // Dart Vader theme (Imperial March) - Star wars
        // Score available at https://musescore.com/user/202909/scores/1141521
        // The tenor saxophone part was used
        Note.AS4, Note.AS4, Note.AS4,   //1
        Note.F5, Note.C6,
        Note.AS5, Note.A5, Note.G5, Note.F6, Note.C6,
        Note.AS5, Note.A5, Note.G5, Note.F6, Note.C6,
        Note.AS5, Note.A5, Note.AS5, Note.G5, Note.C5, Note.C5, Note.C5,
        Note.F5, Note.C6,
        Note.AS5, Note.A5, Note.G5, Note.F6, Note.C6,
        Note.AS5, Note.A5, Note.G5, Note.F6, Note.C6,   //8
        Note.AS5, Note.A5, Note.AS5, Note.G5, Note.C5, Note.C5,
        Note.D5, Note.D5, Note.AS5, Note.A5, Note.G5, Note.F5,
        Note.F5, Note.G5, Note.A5, Note.G5, Note.D5, Note.E5, Note.C5, Note.C5,
        Note.D5, Note.D5, Note.AS5, Note.A5, Note.G5, Note.F5,
        Note.C6, Note.G5, Note.G5, Note.NONE, Note.C5,   //13
        Note.D5, Note.D5, Note.AS5, Note.A5, Note.G5, Note.F5,
        Note.F5, Note.G5, Note.A5, Note.G5, Note.D5, Note.E5, Note.C6, Note.C6,
        Note.F6, Note.DS6, Note.CS6, Note.C6, Note.AS5, Note.GS5, Note.G5, Note.F5,
        Note.C6
    ) to intArrayOf(
        8,
        8,
        8,
        2,
        2,
        8,
        8,
        8,
        2,
        4,
        8,
        8,
        8,
        2,
        4,
        8,
        8,
        8,
        2,
        8,
        8,
        8,
        2,
        2,
        8,
        8,
        8,
        2,
        4,
        8,
        8,
        8,
        2,
        4,
        8,
        8,
        8,
        2,
        -8,
        16,
        -4,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        4,
        8,
        4,
        -8,
        16,
        -4,
        8,
        8,
        8,
        8,
        8,
        -8,
        16,
        2,
        8,
        8,
        -4,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        8,
        4,
        8,
        4,
        -8,
        6,
        4,
        8,
        1,
        4,
        8,
        4,
        8,
        4,
        8,
        1

    )

}
